### ISSUE TITLE
list valid APPIDs

### ISSUE THREAD

**Issue by almson** [libimobiledevice/ifuse#28]
It would be helpful if ifuse could list the APPIDs that are valid for mounting. I am having trouble running ideviceinstaller, and I feel that ifuse should try to offer this crucial functionality itself.

**Comment by clavisound** [comment]
I too had problem to compile ideviceinstaller

I managed to compile both libplist-1.12 to /opt/ and to link ideviceinstaller with lipblist-1.12 in /opt (instead of system libplist)

ldd -v /usr/bin/idevicestaller

        linux-gate.so.1 (0xb773e000)
        libimobiledevice.so.6 => /usr/lib/libimobiledevice.so.6 (0xb76da000)
        libssl.so.1 => /lib/libssl.so.1 (0xb7674000)
        libcrypto.so.1 => /lib/libcrypto.so.1 (0xb74b7000)
        libusbmuxd.so.4 => /usr/lib/libusbmuxd.so.4 (0xb74af000)
        libplist.so.3 => /opt/usr/lib/libplist.so.3 (0xb74a2000) <--- see there!
        libxml2.so.2 => /usr/lib/libxml2.so.2 (0xb7349000)
        libdl.so.2 => /lib/libdl.so.2 (0xb7344000)
        liblzma.so.5 => /lib/liblzma.so.5 (0xb731e000)
        libm.so.6 => /lib/libm.so.6 (0xb72dc000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xb72c2000)
        libplist.so.1 => /usr/lib/libplist.so.1 (0xb72b6000)
        libzip.so.2 => /usr/lib/libzip.so.2 (0xb72a8000)
        libz.so.1 => /lib/libz.so.1 (0xb7292000)
        libc.so.6 => /lib/libc.so.6 (0xb7106000)
        /lib/ld-linux.so.2 (0xb773f000)

Those versions work with me
ideviceinstaller-96775642960696d05098b3cebdab2b0c95a958df <-- linked with plist in /opt/ like this
in configure

libplist_LIBS='-L/opt/usr/lib/ -lplist' libplist_CFLAGS=-I/opt/include/plist/ \
libimobiledevice_CFLAGS=-I/usr/include libimobiledevice_LIBS='-L/usr/lib/ -limobiledevice' \
./configure \
--prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man

libplist-1.12 <-- in /opt/
libplist-1.8 <-- in /usr
libusbmuxd-1.0.10
usbmuxd-1.1.0
ifuse-1.1.3
libimobiledevice-1.2.0

**Comment by nikias** [comment]
I will think about it. What is your problem with compiling ideviceinstaller? You can file an issue in https://github.com/libimobiledevice/ideviceinstaller

**Comment by nikias** [comment]
See commit https://github.com/libimobiledevice/ifuse/commit/df048a1d07628a6a02ed77a8dc0f64930b78acee
